In [1]:
import pandas as pd

In [2]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')
baby_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016395 entries, 0 to 1016394
Data columns (total 7 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Unnamed: 0  1016395 non-null  int64
 1   Id          1016395 non-null  int64
 2   Name        1016395 non-null  object
 3   Year        1016395 non-null  int64
 4   Gender      1016395 non-null  object
 5   State       1016395 non-null  object
 6   Count       1016395 non-null  int64
dtypes: int64(4), object(3)
memory usage: 54.3+ MB

In [3]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

In [4]:

del baby_names['Unnamed: 0']

del baby_names['Id']

baby_names.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

In [5]:
baby_names.groupby("Year").sum().idxmax()

Name      2010
Gender    2007
State     2004
Count     2007
dtype: int64

In [6]:
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

In [7]:
del baby_names["Year"]
names = baby_names.groupby("Name").sum()
names.head()
print(names.shape)
names.sort_values("Count", ascending = 0).head()

(17632, 3)

,Gender,State,Count
Name,,,
Jacob,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,242874
Emma,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,214852
Michael,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,214405
Ethan,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,209277
Isabella,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,204798

In [8]:
len(names)

17632

In [9]:
names.Count.idxmax()

'Jacob'

In [10]:
len(names[names.Count == names.Count.min()])

2578

In [11]:
names[names.Count == names.Count.median()]

           Gender             State  Count
Name
Aishani   FFFFFFF    CACACACACAILNJ     49
Alara    FFFFFFFF  CACACAFLNYNYNYTX     49
Alysse   FFFFFFFF  CACACAMINYTXTXTX     49
Ameir    MMMMMMMM  CAMIMIMIMIMINYOH     49
Anely    FFFFFFFF  CACACACACACACACA     49
...           ...               ...    ...
Sriram    MMMMMMM    CACACACACACATX     49
Trinton  MMMMMMMM  FLLAOKTXTXTXTXTX     49
Vita      FFFFFFF    CACACACACANYNY     49
Yoni     MMMMMMMM  CACACACACACAFLFL     49
Zuleima   FFFFFFF    AZCACACACACACA     49

[66 rows x 3 columns]

In [12]:
names.Count.std()

11006.069467891111

In [ ]:
names.describe()